import { useEffect, useState } from 'react';

import Link from 'next/link';
import Image from 'next/image';
import axios from 'axios';

import PageSeo from '@/components/Layout/PageSeo/PageSeo';

import styles from './index.module.scss';

const Home = () => {
	const [step, setStep] = useState([]);
	const [project, setProject] = useState([]);

	useEffect(() => {
		const fetchHome = async () => {
			try {
				const res = await axios.get('data/home.json');
				const data = res.data;
				setStep(data.steps);
				setProject(data.roadMap);
			} catch (error) {
				console.log(error);
			}
		};

		fetchHome();
	}, []);

	return (
		<PageSeo
			title={'Brazil Alliance'}
			description={'Generated by create next app'}
		>
			<main className={styles['home']}>
				{/* INTRO */}
				<section className={styles['home-intro']}>
					<div
						className={`container ${styles['home-intro-container']}`}
					>
						<div className={styles['home-intro-content']}>
							<div className={styles['home-intro-content_infos']}>
								<h1 className={`tit`}>
									Traduções coletivas e abertas ao público.
								</h1>
								<p>
									Nós somos um grupo aberto de traduções
									coletivas de jogos eletrônicos, com foco
									principal na série Yakuza.
								</p>
								<div className={styles['buttons']}>
									<Link
										href=""
										className={`btn btn-green`}
										aria-label="link traduzir"
									>
										Quero traduzir agora!
									</Link>
									<Link
										href=""
										className={`btn btn-blue`}
										aria-label="link instalador"
									>
										Baixar instalador
									</Link>
								</div>
							</div>
							<div className={styles['home-intro-content_logo']}>
								<Image
									src="/assets/images/logo-big.svg"
									width="342"
									height="251"
									alt="logo bza"
								/>
							</div>
						</div>
					</div>
				</section>

				{/* METHODS */}
				<section className={styles['home-methods']}>
					<div
						className={`container ${styles['home-methods-container']}`}
					>
						<div className={styles['home-methods-content']}>
							<div
								className={styles['home-methods-content_image']}
							>
								<Image
									src="/assets/images/icon-hand.svg"
									width="253"
									height="202"
									alt="image hand"
								/>
							</div>
							<div
								className={styles['home-methods-content_infos']}
							>
								<h1 className={`tit`}>Métodos eficientes</h1>
								<p>
									Nosso método de trabalho utiliza as melhores
									ferramentas e métodos que agilizam o
									processo e ainda mantém qualidade e
									consistência dos textos após as revisões.
								</p>
								<p>
									Os voluntários não precisam pedir nenhum
									tipo de permissão e não precisam fazer
									nenhum tipo de teste para fazer parte da
									equipe.
								</p>
								<p>
									Basta escolher um projeto e iniciar com o
									envio de sugestões. A responsabilidade de
									garantir que as melhores sugestões estejam
									no projeto final é dos revisores e do
									administrador de cada projeto.
								</p>
								<p>
									Não há razão para criar burocracia, esconder
									conteúdo e muito menos cobrar tempo de
									entrega em trabalhos voluntários. Suas
									sugestões são sempre bem-vindas!
								</p>
								<div className={styles['readMore']}>
									<Link href="" aria-label="link read more">
										Leia mais
									</Link>
								</div>
							</div>
						</div>
					</div>
				</section>

				{/* STEPS */}
				<section className={styles['home-steps']}>
					<div
						className={`container ${styles['home-steps-container']}`}
					>
						<div className={styles['home-steps-content']}>
							{step.map(
								({
									id,
									imageSrc,
									alt,
									width,
									height,
									text,
								}) => (
									<div
										key={id}
										className={
											styles['home-steps-content_step']
										}
									>
										<div className={styles['icone']}>
											<Image
												src={imageSrc}
												width={width}
												height={height}
												alt={alt}
											/>
										</div>
										<p>{text}</p>
									</div>
								),
							)}
							{/* step */}
						</div>
					</div>
				</section>

				{/* ROADMAP */}
				<section className={styles['home-roadmap']}>
					<div
						className={`container ${styles['home-roadmap-container']}`}
					>
						<div className={styles['home-roadmap-content']}>
							<div
								className={styles['home-roadmap-content_intro']}
							>
								<h1 className={`tit`}>Roadmap de Projetos</h1>
								<div className={styles['status']}>
									<p>
										<span></span> Pendente
									</p>
									<p>
										<span></span> Em andamento
									</p>
									<p>
										<span></span> Concluído
									</p>
								</div>
							</div>

							<div
								className={
									styles['home-roadmap-content_projects']
								}
							>
								{/* project */}
								{project.map(
									({
										id,
										title,
										status,
										imageSrc,
										inprogress,
										progressCompleted,
									}) => (
										<div
											className={`${styles['project']} ${
												styles[`project-${status}`]
											}`}
										>
											<div
												className={
													styles['project-status']
												}
											>
												<span>{status}</span>
												<p>{title}</p>
											</div>
										</div>
									),
								)}
							</div>
						</div>
					</div>
				</section>
			</main>
		</PageSeo>
	);
};

export default Home;
